### ISSUE TITLE
what happen if a process holding a snapshot crash?

### ISSUE THREAD

**Issue by benoitc** [martinsumner/leveled#156]
Can you describe what happen when a process holding a snapshot crash? will it release it ?

A quick glance in the code shows it is starting a pencillef and at the end of the runner op close it. But what happen if the fold function or the process that execute the runner crash? How is managed the timeout?

**Comment by benoitc** [comment]
reading the code a little more it seems the snapshot will be released during compaction. Is this correct?

**Comment by martinsumner** [comment]
When a snapshot is taken it is registered with the penciller, with one of two timeouts (in seconds):

```
-define(SNAPSHOT_TIMEOUT_LONG, 3600).
-define(SNAPSHOT_TIMEOUT_SHORT, 600).
```

The purpose of registering a snapshot is to say that any sst file process active at he manifest SQN must stay active in case it is required by the snapshot, even when it is remove from the current manifest by compaction.

When an SST file is removed by compaction it enters into the `delete_pending` state, and if it receives no messages it will poll the penciller to see if it can remove itself.  If it can't remove itself (because a snapshot is till active), it will release a phantom snapshot.

The fold that releases a given snapshot, will also timeout any expired snapshots.  So eventually a phantom release will expire the snapshot, and then any delete_pending SST files will be able to delete themselves. 

The same process works in the Inker with Journal snapshots (but with CDB files not SST files going into the `delete_pending` state).

**Comment by benoitc** [comment]
Makes sense. Thanks for the explanation :)
