### ISSUE TITLE
is there any optimisations for the index

### ISSUE THREAD

**Issue by benoitc** [martinsumner/leveled#157]
I see that leveled can store terms attached to an index, is there any optimisations to use it instead of having special keys for it?

**Comment by martinsumner** [comment]
So an index specification can have any erlang term as either the field (which would normally be the index name) or term (the part on the index to be filtered by in the range query).  The actual index entry also has a "value",  which currently is always null.

I've had some ideas as to how and expand and enhance this.  It would be possible to have a different type of index that populated the value, so that queries rather than simply accumulating the results list of (i.e. keys and terms) could accumulate the result of applying a function to the values where the index term is in the range.

An example may be of a people finder.  Say I have records of people and I add an index for DateOfBirth - so I can find all the people keys in a given date of birth range.  But actually that's not that useful a query, and I have a bunch of other interesting facts on each person that I want to make searchable (given name, family name, soundex representation of name, zip/post code, nationality, gender, marital status, postal town, occupation etc).  I could add those facts as a term and make that the value of the index entry.

Now I could do a query for all those born between 1940 and 1950, but add on other facts to check (e.g. nationality = uk, family name sounds like = macleod, gender = male).  When leveled runs the query it could get all the index entries in the range, but apply a function to the value to check if the required facts are present before adding them to the accumulator.  This would provide a single action query that could check the conjunction between a range and a set of facts.

The interesting part then, is that each slot in the sst file has an index to accelerate lookups, which is currently empty for slots containing index terms.  Perhaps in an implementation where index values are a set of facts, that sst slot index could be a bloom filter of all the facts within the slot.  So if the query is for a rare fact, it doesn't need to read every slot - it can skip all those which don't have the fact in the slot.  This would be similar to how the segment-accelerated aae queries currently work.

I've not implemented this yet, but it is on my to-do list.

Is this the sort of thing you were thinking of, or have I missed the point of your question?

**Comment by benoitc** [comment]
@martinsumner no, you went even further than what I expected. I will digest that over the week-end, to see if i can fit the barrel index in.

**Comment by martinsumner** [comment]
One optimisation that is already implemented, is support for regular expressions within 2i queries (which is required for Riak).  so you can query for a range of terms, but it will only return those terms that also match on a regular expression.

There's some examples in the test suite of this being used - https://github.com/martinsumner/leveled/blob/master/test/end_to_end/iterator_SUITE.erl

**Comment by benoitc** [comment]
one last question about it, how index keys are handled when a key expire? are keys always linked to the index keys? Ie, will these index keys be ignored/deleted when the key expires?

**Comment by martinsumner** [comment]
As an object is added, it generates a set of changes for the penciller (the key store part of the database):

https://github.com/martinsumner/leveled/blob/master/src/leveled_bookie.erl#L1952-L1957

These changes generate the index specs and the object specs which are then stored separately.  The TTL is passed into both generators so indexes attached to an object will have the same expiry time as the objects.

When a key (either an object key or an index key) is expired it is not reaped until is reaches the bottom of the LSM tree (this is to stop an old value for an object from being returned if a value that replaces it has retired).  If an object key is found through a fetch, and the TTL has expired, then a not_found will be returned.

Likewise when folding over an index, if an index key is the "dominant" entry for that key (i.e. it has not been replaced), the TTL is checked, and the key (and any key which beneath it in the LSM tree it supersedes) is ignored.

This is the theory.  However, I'm not satisfied there's sufficient testing at present of indexes with a TTL.  So as part of this issue I will add a ct test to prove this behaviour.

**Comment by martinsumner** [comment]
I have some time tomorrow (5h Dec) to work on the test

**Comment by martinsumner** [comment]
https://github.com/martinsumner/leveled/pull/220

There's now a test expiring_indexes/1 in the iterator_SUITE which proves the behaviour of index entries with TTLs set on the objects.

**Comment by benoitc** [comment]
I guess the issue can be closed :) thanks for all the explanations !
