### ISSUE TITLE
retrieving the LSN?

### ISSUE THREAD

**Issue by benoitc** [martinsumner/leveled#255]
Is there a way to easily get the LSN on which a key have been stored? also the one used by the store. I'm thinking to expose it for a transaction engine.

**Comment by martinsumner** [comment]
Sort of, but not quite.

There is a mechanism for the user to define their own tags, and then define what metadata will be returned in responses to HEAD requests - https://github.com/martinsumner/leveled/blob/master/docs/STARTUP_OPTIONS.md#user-defined-tags.

The issue is though, that the `build_head/2` function is only passed metadata extracted from the object, not internal metadata.

I don't think it would be too hard to change that though.  If I get chance next week I will have a look.

**Comment by benoitc** [comment]
thanks , i will have a look as well :)

**Comment by martinsumner** [comment]
Sorry, I forgot to look at this.  I have reminded myself to look again, but I'm away this week, so won't be able to investigate straight away.

**Comment by martinsumner** [comment]
Currently a HEAD request will return metadata only, but the metadata does not include (the internal) SQN.  Rather than extend HEAD, I think it would be better to have a specific API function for returning the SQN of the Key.

This should be relatively quick to implement, and won't break anything.

**Comment by martinsumner** [comment]
https://github.com/martinsumner/leveled/tree/mas-i255-getsqn

**Comment by martinsumner** [comment]
https://github.com/martinsumner/leveled/pull/271

**Comment by benoitc** [comment]
@martinsumner  sorry i didn't have the time to include that. I will report next week as i'm pplanning to provide some backend using leveled
