### ISSUE TITLE
basic_SUITE,fetchput_snapshot,1 fails on otp 19

### ISSUE THREAD

**Issue by russelldb** [martinsumner/leveled#62]
When running `rebar3 ct` on otp-18.3 built from erlang.org/downloads otp-18.3 src tar, all tests pass. The same command run with otp-19.2 fails one test:

    %%% basic_SUITE ==> {failed,{{badmatch,false},
         [{basic_SUITE,fetchput_snapshot,1,
                       [{file,"/Users/russell/dev/e/NHS/leveled/_build/test/lib/leveled/test/end_to_end/basic_SUITE.erl"},
                        {line,304}]},
          {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1529}]},
          {test_server,run_test_case_eval1,6,
                       [{file,"test_server.erl"},{line,1045}]},
          {test_server,run_test_case_eval,9,
                       [{file,"test_server.erl"},{line,977}]}]}}

This issue is just a reminder to investigate.

**Comment by Licenser** [comment]
The case fails because the sleep https://github.com/martinsumner/leveled/blob/4ccd67a3c2ed8125567183dc9cd2310132757219/test/end_to_end/basic_SUITE.erl#L300 is not long enough. While putting it to 20s makes this work again using sleep here seems quite problematic perhaps the right approach would be to take fixed times out of the test? (not sure how)
